export const users = [
  {
    username: "Samin_riz",
    firstName: "Samin",
    lastName: "Rizwan",
    school: "Habib University",
    email: "saminrizwan@gmail.com",
    profilePicture: "https://picsum.photos/200",
    classLevel: "Freshmen",
  },
  {
    username: "hamna_owais",
    firstName: "Hamna",
    lastName: "Owais",
    school: "Bahira University",
    email: "hamna@gmail.com",
    profilePicture: "https://picsum.photos/200",
    classLevel: "Sophomore",
  },
  {
    username: "simrah_imran",
    firstName: "Simrah",
    lastName: "Imran",
    school: "Fast University",
    email: "simrah_imran@example.com",
    profilePicture: "https://picsum.photos/200",
    classLevel: "Junior",
  },
  {
    username: "Maham_Fa",
    firstName: "Maham",
    lastName: "Farooqui",
    school: "IOBM Univerity",
    email: "maham_fa05@example.com",
    profilePicture: "https://picsum.photos/200",
    classLevel: "Senior",
  },
  {
    username: "hiba_rao",
    firstName: "Hiba",
    lastName: "Rao",
    school: "Ned University",
    email: "hiba_rao@example.com",
    profilePicture: "https://picsum.photos/200",
    classLevel: "Freshmen",
  },
];